import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [count  , setCount] = useState(0);

  const increment = () => setCount((count) => count + 1)

  function decrement() {
    count > 0 ? setCount(count - 1) : count
  }

  function reset() {
    setCount(0)
  }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <div className={`container`}>
        <p id="count">{count}</p>
          <ul>
            <li>
              <button className="rainbow" id="increment" onClick={increment}>Increment</button>
              <button className="rainbow" id="decrement" onClick={decrement}>Decrement</button>
              <button className="rainbow" id="reset" onClick={reset}>Reset</button>
            </li>
          </ul>
        </div>
       
      </main>
    </>
  );
}
